/* Archive of Earth design: editorial museum layout, tactile chronology, evidence-first labels. */
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, BookOpen, Filter, Menu, Search, X } from "lucide-react";

const heroImage = "/manus-storage/archive-earth-hero_d7c7ff2e.jpg";
const markImage = "/manus-storage/archive-earth-mark_52aa302c.png";

const periods = [
  { id: "prehistoric", year: "c. 40,000–2,500 BCE", title: "Prehistoric / Rock Art", intro: "The first marks: hunting, ritual, movement, and memory on stone.", development: "Natural pigments and rhythmic silhouettes turn rock shelters into communal archives.", influences: "Early hunter-gatherer communities" },
  { id: "indus", year: "c. 3300–1300 BCE", title: "Indus Valley Civilization", intro: "Urban craft, miniature seals, and an astonishingly precise visual language.", development: "Steatite carving, bronze casting, terracotta, and standardised craft traditions.", influences: "Harappan cities: Mohenjo-daro, Harappa, Dholavira" },
  { id: "mauryan", year: "c. 322–185 BCE", title: "Mauryan Period", intro: "Imperial polish meets the ethical vocabulary of the edict and the stupa.", development: "Highly finished stone carving, monolithic pillars, and early Buddhist monuments.", influences: "Maurya dynasty; Ashoka's patronage" },
  { id: "buddhist", year: "c. 2nd BCE–5th CE", title: "Buddhist Art", intro: "Across Gandhara and Mathura, the Buddha takes sculptural form.", development: "Narrative reliefs, devotional images, and distinct regional approaches to the human figure.", influences: "Buddhist networks; Hellenistic and north Indian traditions" },
  { id: "gupta", year: "c. 320–550 CE", title: "Gupta Period", intro: "A classical balance of inward calm, ideal form, and spiritual presence.", development: "Refined stone sculpture, temple beginnings, and the flourishing of painted caves.", influences: "Gupta court culture; Buddhist and Hindu devotional communities" },
  { id: "medieval", year: "c. 600–1200 CE", title: "Medieval Indian Art", intro: "Temple walls become encyclopaedias of gods, dancers, stories, and desire.", development: "Architectural sculpture, regional temple idioms, and intricate iconographic systems.", influences: "Chalukya, Pallava, Chandela and other regional dynasties" },
  { id: "chola", year: "c. 850–1279 CE", title: "Chola / South Indian Temple Art", intro: "Bronze, procession, and the divine body in motion.", development: "Lost-wax bronze casting and monumental Dravidian temple architecture.", influences: "Chola dynasty; Shaiva and Vaishnava temple cultures" },
  { id: "mughal", year: "c. 1526–1857 CE", title: "Mughal Art", intro: "Observation, empire, and the intimate scale of the illustrated manuscript.", development: "Court ateliers combine Persianate painting with Indian naturalism and portraiture.", influences: "Mughal emperors; Persian, Central Asian and Indian ateliers" },
  { id: "rajput", year: "c. 1500–1900 CE", title: "Rajput & Pahari Painting", intro: "Love, landscape, music, and devotion unfold in saturated miniature worlds.", development: "Regional schools use lyrical line, mineral color, and poetic narrative.", influences: "Rajput courts; Pahari kingdoms; Bhakti poetry" },
  { id: "colonial", year: "c. 1750–1900 CE", title: "Colonial / Company Art", intro: "Indian artists negotiate the gaze, the archive, and a changing market.", development: "Watercolor documentation, hybrid commissions, and new modes of visual description.", influences: "East India Company; colonial survey and collecting" },
  { id: "bengal", year: "c. 1905–1940 CE", title: "Bengal School", intro: "A search for an Indian modernism through wash, line, and inherited memory.", development: "Revivalist and cosmopolitan practices turn away from academic realism.", influences: "Abanindranath Tagore, Nandalal Bose, pan-Asian exchanges" },
  { id: "modern", year: "c. 1940–present", title: "Modern & Contemporary", intro: "Many Indias, many materials: the archive becomes a living argument.", development: "Artists expand the field into abstraction, installation, performance, and public practice.", influences: "Progressive Artists' Group; postcolonial and global conversations" },
];

const artifacts = [
  { id: 1, period: "prehistoric", title: "Bhimbetka Rock Shelters", date: "c. 10,000 BCE", region: "Madhya Pradesh", medium: "Mineral pigments on rock", creator: "Unknown communities", image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Rock_painting%2C_Bhimbetka%2C_Raisen_district%2C_MP%2C_India.jpg", desc: "Layered scenes of animals, people, and movement survive across the rock shelters of central India. Their power lies in the repeated act of looking, returning, and marking place.", context: "The shelters were used across long spans of time, so individual paintings belong to different phases rather than one single moment.", significance: "They offer rare evidence of early image-making as social memory and embodied experience.", facts: ["Bhimbetka is a UNESCO World Heritage Site.", "Many paintings overlap earlier images.", "Dates are approximate and vary by shelter and layer."] },
  { id: 2, period: "indus", title: "Dancing Girl", date: "c. 2500 BCE", region: "Mohenjo-daro, Sindh", medium: "Cast bronze", creator: "Unknown Harappan artist", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dancing_Girl_of_Mohenjo-daro.jpg", desc: "A small bronze figure stands with one hand on her hip, her pose relaxed and self-possessed. The sculpture compresses balance, attitude, and technical confidence into a palm-sized object.", context: "Found at Mohenjo-daro, the figure belongs to the urban craft world of the Indus Valley Civilization.", significance: "Its expressive stance complicates the idea that ancient craft is only formal or ceremonial.", facts: ["The figure is about 10.5 cm tall.", "She wears numerous bangles.", "The artist's identity is unknown."] },
  { id: 3, period: "mauryan", title: "Lion Capital of Ashoka", date: "c. 250 BCE", region: "Sarnath, Uttar Pradesh", medium: "Polished sandstone", creator: "Mauryan workshop; commissioned under Ashoka", image: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Lion_capital_of_Ashoka%2C_Sarnath.jpg", desc: "Four lions sit back-to-back above a circular abacus. The famous capital combines imperial authority with Buddhist symbolism and a remarkable stone polish.", context: "It crowned a pillar at Sarnath, where the Buddha is traditionally believed to have given his first sermon.", significance: "The capital became the state emblem of the Republic of India in 1950.", facts: ["The abacus includes a wheel and animals.", "The original pillar remains at Sarnath.", "The visible emblem shows three lions."] },
  { id: 4, period: "buddhist", title: "Buddha from Gandhara", date: "c. 2nd–3rd century CE", region: "Gandhara, northwest South Asia", medium: "Schist", creator: "Unknown Gandharan sculptor", image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Afghanistan%2C_Gandhara%2C_Hadda%2C_late_Kushan_Period_-_Seated_Buddha_-_1967.39_-_Cleveland_Museum_of_Art.jpg", desc: "Heavy, cascading robes frame a composed face. The image shows how Buddhist devotional sculpture took distinct regional forms across connected trade routes.", context: "Gandhara's visual culture developed at the intersection of Buddhist, Iranian, and Hellenistic traditions.", significance: "The work is often discussed in relation to the emergence of anthropomorphic Buddha imagery.", facts: ["Gandhara is a historical region, not a single city.", "Schist allowed crisp folds and details.", "Attributions and dates are often approximate."] },
  { id: 5, period: "gupta", title: "Seated Buddha from Sarnath", date: "c. 5th century CE", region: "Sarnath, Uttar Pradesh", medium: "Chunar sandstone", creator: "Unknown Gupta-period sculptor", image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg", desc: "The nearly weightless robe, lowered gaze, and balanced hands create an image of concentrated stillness. Form becomes a vehicle for an interior state.", context: "Sarnath was a major Buddhist pilgrimage and artistic centre during the Gupta period.", significance: "The sculpture is a canonical example of Gupta classicism and devotional image-making.", facts: ["The hands show the gesture of teaching.", "The stone surface is exceptionally smooth.", "The exact workshop is unknown."] },
  { id: 6, period: "gupta", title: "Ajanta Cave Paintings", date: "c. 2nd BCE–6th CE", region: "Maharashtra", medium: "Paint on prepared plaster", creator: "Multiple unknown workshops", image: "https://upload.wikimedia.org/wikipedia/commons/2/25/Ajanta_Cave_17-17.jpg", desc: "Figures, gestures, textiles, and narrative episodes move across the cave walls with astonishing visual intelligence. The paintings make compassion legible through faces and bodies.", context: "Ajanta's caves were supported by Buddhist communities and patrons across several centuries.", significance: "They are among the most important surviving bodies of ancient Indian painting.", facts: ["The caves include monasteries and prayer halls.", "Work continued in multiple phases.", "Light and architecture shape how the paintings are seen."] },
  { id: 7, period: "chola", title: "Nataraja", date: "c. 11th century CE", region: "Tamil Nadu", medium: "Cast bronze", creator: "Chola-period workshop", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Shiva_Nataraja.jpg", desc: "Shiva dances within a ring of flame, one foot steady and the other lifted. The bronze makes cosmic motion feel both measured and immediate.", context: "Chola bronzes were made for temple ritual and processions, where the image could travel among devotees.", significance: "Nataraja condenses Shaiva theology, rhythm, destruction, and renewal into a single moving body.", facts: ["The bronze uses the lost-wax process.", "The surrounding flames are part of the iconographic form.", "Chola bronzes were ritual objects, not only gallery sculpture."] },
  { id: 8, period: "medieval", title: "Khajuraho Temple Sculpture", date: "c. 950–1050 CE", region: "Madhya Pradesh", medium: "Sandstone relief", creator: "Chandela-period workshops", image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Khajuraho_India_-_Javari_Temple_-_Sculpture_05.JPG", desc: "The temple surfaces teem with deities, musicians, guardians, lovers, and everyday movement. The sculpture is architectural, social, and cosmological at once.", context: "The Khajuraho complex was built under the Chandela dynasty and included Hindu and Jain temples.", significance: "Its program resists a single reading: erotic imagery sits within a much larger sacred and worldly visual field.", facts: ["The complex originally had more temples than survive today.", "Sculpture is integrated with architecture.", "Interpretation should avoid reducing the site to erotic scenes alone."] },
  { id: 9, period: "mughal", title: "Hamzanama Illustration", date: "c. 1560–1577 CE", region: "Mughal court atelier", medium: "Opaque watercolor and gold on cotton", creator: "Multiple atelier artists", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Hamzanama.jpg", desc: "A crowded, dynamic scene uses saturated color and dramatic gesture to animate the adventures of Amir Hamza. The page is theatrical, narrative, and collaborative.", context: "The Hamzanama was among the ambitious illustrated projects of the early Mughal atelier.", significance: "It shows the court's investment in large-scale storytelling and the exchange of Persianate and Indian pictorial strategies.", facts: ["The original project contained many large-format paintings.", "Artists often worked collaboratively.", "The surviving pages are dispersed across collections."] },
  { id: 10, period: "rajput", title: "Radha and Krishna in the Grove", date: "c. 1780 CE", region: "Kangra, Himachal Pradesh", medium: "Opaque watercolor on paper", creator: "Kangra school; artist unknown", image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Radha_Krishna%2C_circa_18th_century_CE%2C_Kangra_School_of_Art%2C_Allahabad_Museum%2C_Uttar_Pradesh.jpg", desc: "A lyrical landscape stages longing through foliage, distance, and a pair of figures. The small scale invites close, patient looking.", context: "Pahari painters frequently drew on Vaishnava poetry and the emotional vocabulary of bhakti.", significance: "Landscape becomes an emotional participant rather than a neutral setting.", facts: ["Kangra painting is associated with lyrical line.", "Many works draw on the Bhagavata Purana and poetic traditions.", "The exact artist is often unrecorded."] },
  { id: 11, period: "colonial", title: "A Company School Watercolour", date: "c. 1820–1850 CE", region: "Calcutta / north India", medium: "Watercolour on paper", creator: "Artist unknown", image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Painting_of_a_woman_and_two_attendants%2C_Company_School%2C_ca.1820.jpg", desc: "Botanical, architectural, and ethnographic subjects are described with careful observation for colonial patrons and collectors. The image is both document and constructed encounter.", context: "Company painting developed through commissions shaped by British collecting and administrative interests.", significance: "It reveals how representation is entangled with power, mobility, and the market.", facts: ["There was no single Company style.", "Indian artists produced much of the work.", "Titles and dates may derive from later cataloguing."] },
  { id: 12, period: "bengal", title: "Bharat Mata", date: "1905 CE", region: "Bengal", medium: "Tempera and wash on paper", creator: "Abanindranath Tagore", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Bharat_Mata_by_Abanindranath_Tagore.jpg", desc: "A four-armed, saffron-robed figure holds symbols of learning, food, clothing, and spiritual knowledge. The restrained wash technique carries an unmistakable political charge.", context: "Painted during the Swadeshi movement, the image became associated with cultural nationalism.", significance: "It demonstrates how an artwork can operate simultaneously as devotional allegory, political symbol, and modern painting.", facts: ["The work is in the collection of the Victoria Memorial, Kolkata.", "Abanindranath was a key figure of the Bengal School.", "The title translates as Mother India."] },
  { id: 13, period: "modern", title: "Three Girls", date: "1935 CE", region: "India", medium: "Oil on canvas", creator: "Amrita Sher-Gil", image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Amrita_Sher-Gil_Group_of_Three_Girls.jpg", desc: "Three monumental seated figures occupy the canvas with quiet intensity. Their compressed space and inward gaze make modernity feel psychological rather than merely stylistic.", context: "Sher-Gil's work brought together European training and a sustained engagement with Indian subjects and visual cultures.", significance: "The painting is central to discussions of Indian modernism and the politics of looking.", facts: ["Sher-Gil painted the work in 1935.", "She is often described as a foundational figure in modern Indian art.", "The National Gallery of Modern Art, New Delhi holds the work."] },
  { id: 14, period: "modern", title: "Untitled — M. F. Husain", date: "20th century", region: "India", medium: "Oil on canvas", creator: "Maqbool Fida Husain", image: "https://commons.wikimedia.org/wiki/Special:FilePath/M._F._Husain.jpg", desc: "Husain's simplified, angular figures and charged contours turn the canvas into a field of speed and memory. The work stands for the plurality of post-independence Indian modernism.", context: "Husain was associated with the Progressive Artists' Group, formed in Bombay in 1947.", significance: "His practice expanded the vocabulary of Indian painting through cubist structure, myth, cinema, and public life.", facts: ["The exact title and date vary across untitled works.", "Husain worked across painting, film, and design.", "Attributions should be checked against collection records."] },
];

export default function Home() {
  const [selectedPeriod, setSelectedPeriod] = useState("prehistoric");
  const [selectedArtifact, setSelectedArtifact] = useState<typeof artifacts[number] | null>(null);
  const [query, setQuery] = useState("");
  const [region, setRegion] = useState("all");
  const [medium, setMedium] = useState("all");
  const [mobileOpen, setMobileOpen] = useState(false);
  const currentIndex = periods.findIndex((p) => p.id === selectedPeriod);
  const currentPeriod = periods[currentIndex];
  const regions = ["all", ...Array.from(new Set(artifacts.map((a) => a.region)))];
  const mediums = ["all", ...Array.from(new Set(artifacts.map((a) => a.medium)))];
  const filteredArtifacts = useMemo(() => artifacts.filter((a) => {
    const matchesQuery = `${a.title} ${a.date} ${a.period} ${a.region} ${a.medium} ${a.creator} ${a.desc} ${a.context}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (region === "all" || a.region === region) && (medium === "all" || a.medium === medium);
  }), [query, region, medium]);
  const periodArtifacts = filteredArtifacts.filter((a) => a.period === selectedPeriod);

  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const movePeriod = (direction: number) => {
    const next = Math.max(0, Math.min(periods.length - 1, currentIndex + direction));
    setSelectedPeriod(periods[next].id);
    setTimeout(() => scrollTo("timeline"), 20);
  };
  const openArtifact = (artifact: typeof artifacts[number]) => setSelectedArtifact(artifact);
  const nextArtifact = () => {
    if (!selectedArtifact || filteredArtifacts.length === 0) return;
    const index = filteredArtifacts.findIndex((a) => a.id === selectedArtifact.id);
    const nextIndex = index < 0 ? 0 : (index + 1) % filteredArtifacts.length;
    setSelectedArtifact(filteredArtifacts[nextIndex]);
  };

  useEffect(() => {
    if (!selectedArtifact) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setSelectedArtifact(null);
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [selectedArtifact]);

  return <div className="site-shell">
    <header className="topbar">
      <a className="brand" href="#home" aria-label="Indian Art Through Time home"><img src={markImage} alt="Archive seal" /><span>INDIAN ART<br /><em>THROUGH TIME</em></span></a>
      <nav className={mobileOpen ? "nav-links open" : "nav-links"} aria-label="Main navigation">
        <a href="#timeline" onClick={() => setMobileOpen(false)}>Timeline</a><a href="#artifacts" onClick={() => setMobileOpen(false)}>Artifacts</a><a href="#about" onClick={() => setMobileOpen(false)}>About</a><a href="#sources" onClick={() => setMobileOpen(false)}>Sources</a>
      </nav>
      <button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
    </header>

    <main>
      <section id="home" className="hero">
        <div className="hero-copy"><p className="eyebrow">A digital exhibition · Indian Art History CO1</p><h1>Indian Art<br /><i>Through Time</i></h1><p className="hero-sub">Explore thousands of years of Indian artistic heritage through an interactive journey across time.</p><button className="primary-button" onClick={() => scrollTo("timeline")}>Explore the timeline <ArrowDown size={16} /></button><p className="hero-note">12 periods · 14 works · c. 40,000 BCE to the present</p></div>
        <div className="hero-image"><img src={heroImage} alt="Archival museum table with Indian art materials" /><span className="image-caption">Material memory / archive study no. 01</span></div>
      </section>

      <section className="intro-strip"><div className="section-tag">01 / ORIENTATION</div><div className="intro-content"><p className="large-copy">Art history is not a straight line. It is a conversation between materials, beliefs, places, patrons, and people.</p><p className="muted-copy">Move through the timeline to see how images have carried stories across stone, bronze, paper, pigment, and the moving image.</p></div><div className="stat-stack"><div><strong>12</strong><span>periods</span></div><div><strong>40K</strong><span>years of making</span></div><div><strong>14</strong><span>works to explore</span></div></div></section>

      <section id="timeline" className="timeline-section"><div className="section-heading"><div><p className="eyebrow">02 / THE CHRONOLOGY</p><h2>A living archive</h2></div><p className="heading-note">Select a period to open its context. The line is a guide, not a boundary.</p></div><div className="timeline-layout"><aside className="era-rail" aria-label="Historical periods">{periods.map((period, index) => <button key={period.id} className={period.id === selectedPeriod ? "era-link active" : "era-link"} onClick={() => setSelectedPeriod(period.id)}><span className="era-dot">{String(index + 1).padStart(2, "0")}</span><span><small>{period.year}</small>{period.title}</span></button>)}</aside><div className="period-panel"><div className="period-topline"><span>{String(currentIndex + 1).padStart(2, "0")} / 12</span><span className="progress-track"><i style={{ width: `${((currentIndex + 1) / periods.length) * 100}%` }} /></span><span>{Math.round(((currentIndex + 1) / periods.length) * 100)}%</span></div><div className="period-intro"><p className="date-label">{currentPeriod.year}</p><h3>{currentPeriod.title}</h3><p className="period-lede">{currentPeriod.intro}</p><div className="period-facts"><div><span>DEVELOPMENT</span><p>{currentPeriod.development}</p></div><div><span>INFLUENCES</span><p>{currentPeriod.influences}</p></div></div></div><div className="period-artifacts"><div className="subheading"><span>Representative works</span><span>{periodArtifacts.length} entries</span></div>{periodArtifacts.length ? <div className="artifact-row">{periodArtifacts.map((a) => <button className="artifact-card" key={a.id} onClick={() => openArtifact(a)}><div className="artifact-thumb"><img src={a.image} alt={a.title} /><span>View work <ArrowRight size={13} /></span></div><div className="artifact-meta"><small>{a.date}</small><strong>{a.title}</strong><em>{a.region}</em></div></button>)}</div> : <p className="empty-state">No works match the current search and filters.</p>}</div><div className="period-controls"><button aria-label="Go to previous period" onClick={() => movePeriod(-1)} disabled={currentIndex === 0}><ArrowLeft size={16} /> Previous</button><button aria-label="Go to next period" onClick={() => movePeriod(1)} disabled={currentIndex === periods.length - 1}>Next period <ArrowRight size={16} /></button></div></div></div></section>

      <section id="artifacts" className="collection-section"><div className="section-heading"><div><p className="eyebrow">03 / THE COLLECTION</p><h2>Meet the objects</h2></div><p className="heading-note">Search the collection by title, place, material, or period.</p></div><div className="filter-bar"><div className="search-field"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search the archive" aria-label="Search artifacts" /></div><div className="select-wrap"><Filter size={15} /><select value={region} onChange={(e) => setRegion(e.target.value)} aria-label="Filter by region"><option value="all">All regions</option>{regions.slice(1).map((r) => <option key={r}>{r}</option>)}</select></div><div className="select-wrap"><select value={medium} onChange={(e) => setMedium(e.target.value)} aria-label="Filter by medium"><option value="all">All materials</option>{mediums.slice(1).map((m) => <option key={m}>{m}</option>)}</select></div></div><div className="collection-grid">{filteredArtifacts.map((a, index) => <button className={index === 0 ? "collection-card featured" : "collection-card"} key={a.id} onClick={() => openArtifact(a)}><img src={a.image} alt={a.title} /><div className="collection-overlay"><small>{a.date} · {a.period}</small><strong>{a.title}</strong><span>{a.region} <ArrowRight size={14} /></span></div></button>)}</div></section>

      <section id="about" className="about-section"><div className="section-tag">04 / ABOUT THE EXHIBITION</div><div className="about-copy"><h2>Look closely.<br /><i>Context changes everything.</i></h2><p>This student-led digital exhibition follows a broad arc through Indian art history while leaving room for uncertainty, regional difference, and the many hands behind a work. It is designed as a starting point for careful looking—not a replacement for museum collections, conservation records, or specialist scholarship.</p><div className="about-signoff"><BookOpen size={18} /><span>Built for Indian Art History · CO1<br /><em>Dates and classifications are approximate where noted.</em></span></div></div></section>
      <section id="sources" className="sources-section"><div><p className="eyebrow">05 / SOURCES & METHODS</p><h2>Where the labels lead</h2></div><div className="source-list"><p>Object information has been written from established art-historical references and collection records. Images are linked to publicly available Wikimedia Commons files for educational use; individual image rights and collection attributions should be checked before publication.</p><div className="source-links"><a href="https://whc.unesco.org/en/list/925/" target="_blank" rel="noreferrer">UNESCO · Bhimbetka Rock Shelters <ArrowRight size={14} /></a><a href="https://www.metmuseum.org/toah/" target="_blank" rel="noreferrer">The Metropolitan Museum · Heilbrunn Timeline <ArrowRight size={14} /></a><a href="https://www.britishmuseum.org/collection" target="_blank" rel="noreferrer">British Museum · Collection research <ArrowRight size={14} /></a></div></div></section>
    </main>

    <footer><div className="brand footer-brand"><img src={markImage} alt="Archive seal" /><span>INDIAN ART<br /><em>THROUGH TIME</em></span></div><p>Made for slow looking and better questions.</p><span>© 2026 · Educational project</span></footer>

    {selectedArtifact && <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && setSelectedArtifact(null)}><article className="artifact-modal" role="dialog" aria-modal="true" aria-labelledby="artifact-title"><button className="modal-close" onClick={() => setSelectedArtifact(null)} aria-label="Close artifact detail"><X size={20} /></button><div className="modal-image"><img src={selectedArtifact.image} alt={selectedArtifact.title} /></div><div className="modal-content"><p className="eyebrow">{selectedArtifact.period} · {selectedArtifact.date}</p><h2 id="artifact-title">{selectedArtifact.title}</h2><div className="label-grid"><div><span>REGION</span><strong>{selectedArtifact.region}</strong></div><div><span>MEDIUM</span><strong>{selectedArtifact.medium}</strong></div><div><span>CREATOR</span><strong>{selectedArtifact.creator}</strong></div></div><div className="detail-copy"><h4>About the work</h4><p>{selectedArtifact.desc}</p><h4>Historical context</h4><p>{selectedArtifact.context}</p><h4>Why it matters</h4><p>{selectedArtifact.significance}</p></div><div className="facts"><span>FIELD NOTES</span>{selectedArtifact.facts.map((fact) => <p key={fact}>↳ {fact}</p>)}</div><button className="next-artifact" onClick={nextArtifact}>Explore next artifact <ArrowRight size={16} /></button></div></article></div>}
  </div>;
}
